### ISSUE TITLE
Web GUI not connecting

### ISSUE THREAD

**Issue by Coolbud01** [CmdrVasquess/bcplus#4]
IP address 169.254.16.235:1337 for web GUI times out.  Attempted to connect via my cellular network and from within my home network.

**Comment by CmdrVasquess** [comment]
The address from above is not a private IP address, as I would expect. Private IPv4 address range is 192.168.x.y, ~172.16.x.y, and 10.x.y.z. Problem is that my IP guessing algo is quite dumb. If you dare to use the cmd command line tool you could try the ipconfig command. That should show you all yout IP addresses. It is expected that your public IP won't work until you do some fancy tweaking to your network config.
Ill try to improve my algo! Until then try to use the ipconfig tool.

**Comment by CmdrVasquess** [comment]
Another thing could be the Windows Firewall. You have to permit network connections for BCplus. Otherwise one cannot connet to the BC+ web server.

**Comment by Coolbud01** [comment]
I checked the firewall settings before submitting; everything was in order there.  I was assuming the IP address, with the port 1337, was a server you were hosting.  I have a static IP that's much different, and my dhcp server is the standard 192.168.1.x.

Is this program serving the web gui from the machine it's running on, like a localhost setup?

**Comment by CmdrVasquess** [comment]
Exactly! A significant part of BC+ is the web server. I.e. there is a web server running on the same machine as your E:D installation. To reach that web server you have to somehow address that machine – and on that machine the web server. Most private people don't have a DNS running on their local network which is why you cannot connect to BC+ using a nice name. Instead you have to use the IP address. But the IP address is not enough. You also need the port number of the web server on the machine. To avoid collisions with standard web servers (port 80, by convention) BC+ uses a different port number (default 1337). But you can set the port number to any other free port number.
So as long as you are able to figure out the IP address of the PC running the BC+ (and E:D) and you choose the right port and there is no firewall blocking the IP traffic the thing should work.

My only idea for a fix is to list URLs for all IP addresses that BC+ finds for the computer so that a user can try until one works. Anything else probably would be an installer running with admin privileges. Currently not my game… I chose Go to be platform independent

**Comment by Coolbud01** [comment]
Ok, I just put in 'localhost:1337' and it worked.

So, this bug report originated from the prompt that I received after I first ran the program.  The program tells the user "for web GUI open 'http://169.254.16.235:1437/' in your browser".

That can mislead folks if they're not savvy.  I'm not sure how other OS's handle localhost or 127.0.0.1, but it should be standard across them.  Might consider prompting the user to type in '127.0.0.1:1337' to Access the web gui.

Thanks for responding so quickly.  I'll give the program a run thru tonight.

**Comment by Coolbud01** [comment]
Ah, disregard the localhost thing... you need to be able to tell your users how to connect to the machine running the program, in case they want to use a tablet or laptop to access it.

So, I can connect to my gaming computer, running BCPlus, from my phone that's on the same Wi-Fi network, by putting in 192.168.1.13:1337.  That works.

Also, I port forwarded 1337 to my machine running BCPlus, so I can access it from outside my lan.  That works too.  (Check if you want; my static IP is 98.174.173.50:1337)

Soo... back to 169.254.16.235:1337 - where did that IP even come from?

Possible solution is to make a readme with basic instructions for the user to determine their own local IP and instructions on how to access the web gui from the host machine, and how to access it from an external device.  Since most Elite players are older, you might have quite a few folks messaging you for help lol.

**Comment by CmdrVasquess** [comment]
Good to hear that it technially is OK. - How to make the connection easy for every user is just a challenge. Probably docs is the best idea. However I'd be thankful for every good advise...

**Comment by CmdrVasquess** [comment]
Terminal list all detected potential URLs to connect.
